# Autogenerated by nbdev

d = { 'settings': { 'audience': 'Developers',
                'author': 'Javier Vera',
                'author_email': 'javierveraolmos@gmail.com',
                'branch': 'main',
                'copyright': 'Put your copyright info here',
                'custom_sidebar': 'False',
                'description': 'Solution for the mediavida challenge 2',
                'doc_baseurl': '/futurama_frames_detection/',
                'doc_host': 'https://Javier Vera.github.io',
                'doc_path': '_docs',
                'git_url': 'https://github.com/Javier Vera/futurama-frames-detection/',
                'host': 'github',
                'keywords': 'ml pytorch',
                'language': 'English',
                'lib_name': 'futurama_frames_detection',
                'lib_path': 'futurama_frames_detection',
                'license': 'apache2',
                'min_python': '3.8',
                'nbs_path': '.',
                'recursive': 'False',
                'repo': 'futurama-frames-detection',
                'requirements': 'fastcore pandas numpy matplotlib pytorch torchvision Pillow',
                'status': '2',
                'title': 'futurama_frames_detection',
                'tst_flags': 'notest',
                'user': 'Javier Vera',
                'version': '0.0.1'},
  'syms': { 'futurama_frames_detection.core': { 'futurama_frames_detection.core.FuturamaDataset': 'https://Javier '
                                                                                                  'Vera.github.io/futurama_frames_detection/core.html#futuramadataset',
                                                'futurama_frames_detection.core.FuturamaResnet': 'https://Javier '
                                                                                                 'Vera.github.io/futurama_frames_detection/core.html#futuramaresnet',
                                                'futurama_frames_detection.core.FuturamaResnet.forward': 'https://Javier '
                                                                                                         'Vera.github.io/futurama_frames_detection/core.html#futuramaresnet.forward',
                                                'futurama_frames_detection.core.calc_results': 'https://Javier '
                                                                                               'Vera.github.io/futurama_frames_detection/core.html#calc_results',
                                                'futurama_frames_detection.core.create_submission': 'https://Javier '
                                                                                                    'Vera.github.io/futurama_frames_detection/core.html#create_submission',
                                                'futurama_frames_detection.core.criterion': 'https://Javier '
                                                                                            'Vera.github.io/futurama_frames_detection/core.html#criterion',
                                                'futurama_frames_detection.core.training': 'https://Javier '
                                                                                           'Vera.github.io/futurama_frames_detection/core.html#training'}}}